dataset:
  name: AdvBench
  path: eval-anything/eval_anything/benchmarks/safedata/harmful_behaviors.csv
  split: train
  size:
  modality: text-to-text
  default_task_list: ["AdvBench"]
  # /share/project/znh/eval/eval_anything/data
task:
  - name: AdvBench
