dataset:
  name: BeaverTails
  path: eval-anything/eval_anything/benchmarks/safedata/BeaverTails-Evaluation.json
  split: train
  size:
  modality: text-to-text
  default_task_list: ["BeaverTails"]
  # /share/project/znh/eval/eval_anything/data
task:
  - name: BeaverTails
