dataset:
  name: Anthropics
  path: eval-anything/eval_anything/benchmarks/safedata/output.json
  split: train
  size:
  modality: text-to-text
  default_task_list: ["Anthropics"]
  # /share/project/znh/eval/eval_anything/data
task:
  - name: Anthropics