dataset:
  name: Cona
  path: eval-anything/eval_anything/benchmarks/safedata/split_instructions.json
  split: train
  size:
  modality: text-to-text
  default_task_list: ["Cona"]
  # /share/project/znh/eval/eval_anything/data
task:
  - name: Cona
