  # Evaluation configurations
  eval_cfgs:
    # Output directory
    output_dir: ../output
    # Cache directory, if not specified, cache will not be saved
    cache_dir: ../cache
    # Unique identifier for current task
    task_uid: 111
    # benchmark name and task name, if the task list is empty, all tasks will be evaluated
    benchmarks: {
      "mmmu": ["Accounting"]
      }
    # Num shot
    n_shot: {
      "mmmu": 5
      }
    # Chain of thought
    cot: {
      "mmmu": False
      }
  # The model configurations
  model_cfgs:
    # Pretrained model unique identity
    model_id: Llama3.1-8B-Instruct
    # Pretrained model name or path
    model_name_or_path: /aifs4su/yaodong/models/llama3.1/Meta-Llama-3.1-8B-Instruct
    # Model type ("LM" or "MM")
    model_type: "LM"
    # Chat template
    chat_template: Llama3
  infer_cfgs:
    # Inference backend
    infer_backend: "vllm"
    # Whether to trust remote code
    trust_remote_code: True
    # The max token length
    model_max_length: 2048
    # The max new tokens
    max_new_tokens: 512
    # The number of Output
    num_output: 1
    # Top-K
    top_k: 50
    # Top-P
    top_p: 0.95
    # Temperature
    temperature: 0.
    # Prompt Logprobs
    prompt_logprobs: 0
    # Logprobs
    logprobs: 20
    # Beam Search
    beam_search: False
    # Beam Search size
    num_beams: null
    # Number of GPUs
    num_gpu: 8
    # Available GPU IDs. If not specified, first num_gpu GPUs will be used.
    gpu_ids: [0,1]
    # GPU utilization
    gpu_utilization: 0.8
    