  # Evaluation configurations
  eval_cfgs:
    # Output directory
    output_dir: null
    # Cache directory, if not specified, cache will not be saved
    cache_dir: null
    # Unique identifier for current task
    task_uid: null
    # benchmark name and task name, if the task list is empty, all tasks will be evaluated
    benchmarks: {
      "gsm8k": ["main"], 
      "agieval": []
      }
    # Num shot
    n_shot: {
      "gsm8k": 5,
      "agieval": 0
      }
    # Chain of thought
    cot: {
      "gsm8k": False,
      "agieval": False
      }
    # Evaluation metrics
    metrics: {
      "gsm8k": ['accuracy'],
      "agieval": []
      }
  # The model configurations
  model_cfgs:
    # Pretrained model unique identity
    model_id: null
    # Pretrained model name or path
    model_name_or_path: null
    # Model type ("LM" or "MM")
    model_type: "LM"
    # Chat template
    chat_template: null
  infer_cfgs:
    # Inference backend
    infer_backend: "vllm"
    # Whether to trust remote code
    trust_remote_code: True
    # The max token length
    model_max_length: 2048
    # The max new tokens
    max_new_tokens: 512
    # Top-K
    top_k: 50
    # Top-P
    top_p: 0.95
    # Temperature
    temperature: 0.5
    # Beam Search
    beam_search: False
    # Beam Search size
    num_beams: null
    # Number of GPUs
    num_gpu: 8
    # Available GPU IDs. If not specified, first num_gpu GPUs will be used.
    gpu_ids: []
    # GPU utilization
    gpu_utilization: 0.8
    