# ============================================
# 评测配置：
#   - 数据集hf路径
#   - 数据集split
#   - 数据集size
#   - 数据集模态
#   - 评测方式（multiple choice / generation / ...）
#   - 评测指标（accuracy / ...）
#   - 是否支持few_shot
#   - 选项编号形式（ABCD或1234...），判断对错时的标识(true/false或者1/0...)
# ============================================
dataset:
  name: mmmu
  path: MMMU/MMMU
  split: validation
  size: 
  modality: text-image-to-text
  fewshot_data_path: MMMU/MMMU
  fewshot_data_name: "{task_name}"
  fewshot_data_split: dev
  cot_fewshot_data_path: null
  cot_fewshot_data_name: null
  cot_fewshot_data_split: null
  max_shot: 5
  default_task_list: ["Architecture_and_Engineering"]
task: 
  - name: Architecture_and_Engineering
    type: MultiChoice # Placeholder, because MMMU label question type for each single question instead of task
    data_files: null
    question_key: question
    answer_key: options
    ground_truth_key: answer
    candidate_labels: ["A", "B", "C", "D"]
    avalable_evaluate_tools: ["match_open_ended"]
answer_extractor:
  - name: match_open_ended
    function: regex_match_open
    args:
      match_index: -1   # Index for multiple choice
metrics:
  - name: accuracy
    function: accuracy
    args:
overall_metrics:
  - name: average
    function: average_across_tasks
    args:
      null
  